version: '3.7'
services:
  chrome:
    image: selenium/node-chrome-debug:3.141.59-yttrium
    ports:
      - 5901:5900
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1600
      SCREEN_HEIGHT: 1024
    deploy:
      replicas: 3
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  firefox:
    image: selenium/node-firefox-debug:3.141.59-yttrium
    ports:
      - 5902:5900
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1600
      SCREEN_HEIGHT: 1024
    deploy:
      replicas: 3
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  hub:
    image: selenium/hub:3.141.59-yttrium
    ports:
      - "4444:4444"
